version: 0.1.{build}

skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

install:
  - ps: $env:Path = "C:\Program Files\Git\bin;$env:Path"

before_build:
  - cmd: dotnet restore -v Minimal

build_script:
  - cmd: dotnet build -c Release

test_script:
  - bash build/coverage.sh

after_test:
  - cmd: dotnet pack -c Release --output nupkgs

artifacts:
  - path: 'nupkgs\*.nupkg'
    name: nuget-packages